version: 0.2

phases:
  install:
    # runtime-versions:
    #   dotnet: 8.0
    commands:
      - echo Installing Docker...
      - sudo yum update -y
      - sudo yum install -y docker
      # - sudo systemctl start docker
      - nohup dockerd &  # Start Docker in the background
      # - sudo usermod -a -G docker $USER
      # - sudo chmod 666 /var/run/docker.sock
      - echo Docker installation completed.
      - sudo yum install -y git
      - echo Git installation completed.
      # - echo Installing .NET Core dependencies...
      # - cd /src
      # - dotnet restore Identity/Edc.Identity.WebApi/Edc.Identity.WebApi.csproj

  pre_build:
    commands:
      - echo Cloning GitHub repository...
      - git clone https://github.com/eli78435/connector.git
      - cd connector
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/s3w1g3y7/edc/repo
      - echo Pre-build completed.

  build:
    commands:
      - echo Building Docker image...
      - docker build -t identity:latest ./src
  #     - docker tag identity:latest <your-ecr-repository-uri>/<your-docker-image-name>:latest
      - echo Docker build image completed.

  # post_build:
  #   commands:
  #     - echo Pushing Docker image to Amazon ECR...
  #     - docker push <your-ecr-repository-uri>/<your-docker-image-name>:latest
  #     - echo Build completed.

artifacts:
  files:
    - '**/*'
  discard-paths: no